// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJFhuwFba-dMjYIKPcXtbJ-no28Th_h4Q',
    appId: '1:632475562476:web:d2e780a15720d8bf0290c9',
    messagingSenderId: '632475562476',
    projectId: 'infico-3bc0f',
    authDomain: 'infico-3bc0f.firebaseapp.com',
    storageBucket: 'infico-3bc0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQEqqjdBXIXVrdfNDrjjlSiyVuV5F5CFI',
    appId: '1:632475562476:android:4bbfd4a84330467e0290c9',
    messagingSenderId: '632475562476',
    projectId: 'infico-3bc0f',
    storageBucket: 'infico-3bc0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClpc6zK9PmQVzq58mcJIjGSwQ2XqJZ274',
    appId: '1:632475562476:ios:73be130e9bce25020290c9',
    messagingSenderId: '632475562476',
    projectId: 'infico-3bc0f',
    storageBucket: 'infico-3bc0f.firebasestorage.app',
    iosClientId: '632475562476-trg9i7o5bqmnlbcdi1q2eaobug4po9ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClpc6zK9PmQVzq58mcJIjGSwQ2XqJZ274',
    appId: '1:632475562476:ios:73be130e9bce25020290c9',
    messagingSenderId: '632475562476',
    projectId: 'infico-3bc0f',
    storageBucket: 'infico-3bc0f.firebasestorage.app',
    iosClientId: '632475562476-trg9i7o5bqmnlbcdi1q2eaobug4po9ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJFhuwFba-dMjYIKPcXtbJ-no28Th_h4Q',
    appId: '1:632475562476:web:0c5e0aa75940d59d0290c9',
    messagingSenderId: '632475562476',
    projectId: 'infico-3bc0f',
    authDomain: 'infico-3bc0f.firebaseapp.com',
    storageBucket: 'infico-3bc0f.firebasestorage.app',
  );
}
